name: Run Telegram Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Restarts every 5 minutes to prevent timeouts

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.bo }}
      run: python3 bot.py
